name: Ubuntu CI

on:
  push:
    branches-ignore:
      # Exclude the push event for exported diffs, because the CI for export
      # should have been covered by GitHub Actions triggered by pull requests.
      - 'export-D+'
  pull_request:

concurrency:
  # If the workflow is triggered by a pull request, then cancel previous runs
  # for the same pull request, which share the same `github.ref`, otherwise the
  # run ID is used to identify the concurrency group, which is a no-op because
  # the run ID is always unique for each trigged event.
  group: ubuntu-ci-${{ github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: true

# OUT needs to be global. Ideally it would be local to the job so we could
# store it in ${{ runner.temp }} instead of the checkout directory.
# Unfortunately this is hitting some GitHub Action inconsistency with `env`:
# https://github.com/actions/runner/issues/480
env:
  OUT: ${{ format('{0}/out', github.workspace) }}

jobs:
  build_deb:
    name: Build HHVM .deb
    runs-on: 16-core
    container:
      image: ubuntu:focal
      env:
        DISTRO: ubuntu-20.04-focal
        IS_NIGHTLY: 1
    steps:
    - name: Installing git
      run: apt update -y && apt install -y git
    - name: Fetching HHVM and its submodules
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Installing HHVM deps and building HHVM
      run: ci/bin/make-debianish-package

    - name: ls on output directory
      run: "ls $OUT"

    - name: Uploading artifacts
      uses: actions/upload-artifact@v3
      with:
        name: out-directory
        path: ${{ env.OUT }}

  run_quick_tests:
    name: Run HHVM quick tests
    runs-on: 16-core
    needs: build_deb
    container:
      image: ubuntu:focal
    steps:
    - name: Checkout HHVM
      uses: actions/checkout@v3

    - name: Download .deb from build job
      uses: actions/download-artifact@v2

    - name: Install hhvm.deb
      run: sudo apt-get install ./hhvm.deb

    - name: Run HHVM quick tests
      run: hhvm hphp/test/run.php quick

  run_all_tests:
    name: Run all HHVM tests
    runs-on: 16-core
    needs: build_deb
    container:
      image: ubuntu:focal
    steps:
    - name: Checkout HHVM
      uses: actions/checkout@v3

    - name: Download .deb from build job
      uses: actions/download-artifact@v2

    - name: Install hhvm.deb
      run: sudo apt-get install ./hhvm.deb

    - name: Set up locales
      run: |
        sudo tee -a /etc/locale.gen << EOF
        de_DE.UTF-8 UTF-8
        de_DE ISO-8859-1
        de_DE@euro ISO-8859-15
        en_GB.UTF-8 UTF-8
        en_GB ISO-8859-1
        en_GB.ISO-8859-15 ISO-8859-15
        en_US.UTF-8 UTF-8
        en_US ISO-8859-1
        en_US.ISO-8859-15 ISO-8859-15
        es_ES.UTF-8 UTF-8
        es_ES ISO-8859-1
        es_ES@euro ISO-8859-15
        fr_FR.UTF-8 UTF-8
        fr_FR ISO-8859-1
        fr_FR@euro ISO-8859-15
        pt_PT.UTF-8 UTF-8
        pt_PT ISO-8859-1
        pt_PT@euro ISO-8859-15
        tr_TR.UTF-8 UTF-8
        tr_TR ISO-8859-9
        zh_CN.UTF-8 UTF-8
        zh_CN.GB18030 GB18030
        zh_CN.GBK GBK
        zh_CN GB2312
        EOF
    - name: Configure locales
      run: dpkg-reconfigure -frontend=noninteractive locales

    - name: Run HHVM tests
      run: hhvm hphp/test/run.php -x hphp/test/cmake_builds_excluded_tests slow

  run_all_tests_repo:
    name: Run all HHVM tests (repo mode)
    runs-on: 16-core
    needs: build_deb
    container:
      image: ubuntu:focal
    steps:
    - name: Checkout HHVM
      uses: actions/checkout@v3

    - name: Download .deb from build job
      uses: actions/download-artifact@v2

    - name: Install hhvm.deb
      run: sudo apt-get install ./hhvm.deb

    - name: Set up locales
      run: |
        sudo tee -a /etc/locale.gen << EOF
        de_DE.UTF-8 UTF-8
        de_DE ISO-8859-1
        de_DE@euro ISO-8859-15
        en_GB.UTF-8 UTF-8
        en_GB ISO-8859-1
        en_GB.ISO-8859-15 ISO-8859-15
        en_US.UTF-8 UTF-8
        en_US ISO-8859-1
        en_US.ISO-8859-15 ISO-8859-15
        es_ES.UTF-8 UTF-8
        es_ES ISO-8859-1
        es_ES@euro ISO-8859-15
        fr_FR.UTF-8 UTF-8
        fr_FR ISO-8859-1
        fr_FR@euro ISO-8859-15
        pt_PT.UTF-8 UTF-8
        pt_PT ISO-8859-1
        pt_PT@euro ISO-8859-15
        tr_TR.UTF-8 UTF-8
        tr_TR ISO-8859-9
        zh_CN.UTF-8 UTF-8
        zh_CN.GB18030 GB18030
        zh_CN.GBK GBK
        zh_CN GB2312
        EOF
    - name: Configure locales
      run: dpkg-reconfigure -frontend=noninteractive locales

    - name: Run HHVM tests
      run: hhvm hphp/test/run.php --repo -x hphp/test/cmake_builds_excluded_tests slow
